/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Smktelkom
 */
public class Atm_Bank_ extends javax.swing.JFrame {
    
    String str, str1;
    int choice,z,pin=1234,counter=0,a=3;
    int t,s,r,tab=5000000;
    

    /**
     * Creates new form Atm_Bank_
     */
    public Atm_Bank_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Penarikan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ISaldo = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        Penyetoran = new javax.swing.JButton();
        Bantuan2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Penarikan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Penarikan.setText(">");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        getContentPane().add(Penarikan);
        Penarikan.setBounds(320, 210, 40, 40);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Penarikan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 180, 70, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lakukan Transaksi");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 10, 180, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transfer");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 120, 60, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Exit");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 180, 100, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Penyetoran");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 60, 100, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bantuan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 120, 100, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Informasi Saldo");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 60, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 30, 260, 240);

        ISaldo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ISaldo.setText(">");
        ISaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISaldoActionPerformed(evt);
            }
        });
        getContentPane().add(ISaldo);
        ISaldo.setBounds(320, 90, 40, 40);

        Transfer.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Transfer.setText(">");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(320, 150, 40, 40);

        bExit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bExit.setText("<");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(20, 210, 40, 40);

        Penyetoran.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Penyetoran.setText("<");
        Penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyetoranActionPerformed(evt);
            }
        });
        getContentPane().add(Penyetoran);
        Penyetoran.setBounds(20, 90, 40, 40);

        Bantuan2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Bantuan2.setText("<");
        Bantuan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanActionPerformed(evt);
            }
        });
        getContentPane().add(Bantuan2);
        Bantuan2.setBounds(20, 150, 40, 40);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void BantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanActionPerformed
        JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",1);
    }//GEN-LAST:event_BantuanActionPerformed

    private void ISaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISaldoActionPerformed
        int tab = 5000000;
        JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab); //informasi saldo
    }//GEN-LAST:event_ISaldoActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah transfer: " ); //menabung
        r = Integer.parseInt(str1);
        trans hasil = new trans();
        hasil.transfer(tab, r);
        tab =hasil.getSaldo();
    }//GEN-LAST:event_TransferActionPerformed

    private void PenyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyetoranActionPerformed
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
        s = Integer.parseInt(str1);
        setor hasil = new setor();
        hasil.menabung(tab, s);
        tab =hasil.getSaldo();
    }//GEN-LAST:event_PenyetoranActionPerformed

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
        t = Integer.parseInt(str1);
        tarik mengambil = new tarik();
        mengambil.ambil(tab,t);
        tab =mengambil.getSaldo();
    }//GEN-LAST:event_PenarikanActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atm_Bank_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atm_Bank_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atm_Bank_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atm_Bank_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atm_Bank_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton Bantuan1;
    private javax.swing.JButton Bantuan2;
    private javax.swing.JButton ISaldo;
    private javax.swing.JButton Penarikan;
    private javax.swing.JButton Penyetoran;
    private javax.swing.JButton Transfer;
    private javax.swing.JButton bExit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

        private static class setor {
                private int saldo;
            public void menabung (int bal, int s){
            if (s%100!=0) {
                JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima "
                        + "uang koin \nSilahkan ulangi kembali!", "Transaksi gagal", 0);              
            } else if (s<50000) {
                JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai "
                        + "adalah Rp 50000,00","ERROR",0);
            } else if (s>=50000) {
                saldo = bal+s;
                JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : "+saldo);
            }
        }
        public int getSaldo(){
            return saldo;
        }
        
        }

    private static class tarik {
        public int saldo;
        public void ambil(int tab, int t){
        if (t%100!=0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima "
                    + "uang koin \nSilahkan ulangi kembali!", "Transaksi gagal", 0);              
        } else{ 
            if (t<tab) {
            JOptionPane.showMessageDialog(null, "Saldo ANda tidak mencukupi"
                    + "\nSIlahkan lakukan penyetoran","Transaksi Gagl",0);
            } else if (t<50000) {
                JOptionPane.showMessageDialog(null, "Besaran minimal pengambilan"
                    + " tunai adalah Rp 50000","Transaksi Gagal",0);
               
            } else {
                saldo = tab-t;
                JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : "+saldo);
                if (tab<=50000) {
                    JOptionPane.showMessageDialog(null, "Saldo minimal harus Rp "
                            + "50000,00, Segera lakukan penyetoran untuk "
                            + "menghindari penutupan akun.","CAUTION",2);
                }
            }
        }
    }
        public int getSaldo(){
            return saldo;
        }
    }

    private static class trans {
        private int saldo;
            public void transfer (int bal, int r){
            if (r%100!=0) {
                JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima "
                        + "uang koin \nSilahkan ulangi kembali!", "Transaksi gagal", 0);              
            } else if (r<50000) {
                JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai "
                        + "adalah Rp 50000,00","ERROR",0);
            } else if (r>=50000) {
                saldo = bal-r;
                JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : "+saldo);
            }
        }
        public int getSaldo(){
            return saldo;
        }
    }
}
